from __future__ import annotations

from copy import deepcopy
from typing import Any, Dict, List


LEGACY_COMMANDS: Dict[str, Dict[str, Any]] = {
    "iwv": {
        "name": "iwv",
        "label": "IWV",
        "description": "Compute integrated water vapor for the selected date and hour.",
        "example": "iwv,20260116,1",
        "parameters": [
            {
                "name": "date",
                "label": "Date",
                "type": "string",
                "input_type": "text",
                "required": True,
                "placeholder": "20260116",
                "help": "Date in YYYYMMDD format. Do not prefix it with A.",
                "pattern": "^[0-9]{8}$",
            },
            {
                "name": "hour",
                "label": "Hour",
                "type": "integer",
                "input_type": "number",
                "required": True,
                "placeholder": "1",
                "help": "Hour as an integer from 0 to 23. Use 0 for the daily series when supported by the legacy backend.",
                "min": 0,
                "max": 23,
                "step": 1,
            },
        ],
    },
    "opacity": {
        "name": "opacity",
        "label": "Opacity",
        "description": "Compute atmospheric opacity for the selected date, hour, and observing frequency.",
        "example": "opacity,20260116,1,86.3",
        "parameters": [
            {
                "name": "date",
                "label": "Date",
                "type": "string",
                "input_type": "text",
                "required": True,
                "placeholder": "20260116",
                "help": "Date in YYYYMMDD format. Do not prefix it with A.",
                "pattern": "^[0-9]{8}$",
            },
            {
                "name": "hour",
                "label": "Hour",
                "type": "integer",
                "input_type": "number",
                "required": True,
                "placeholder": "1",
                "help": "Hour as an integer from 0 to 23. Use 0 for the daily series when supported by the legacy backend.",
                "min": 0,
                "max": 23,
                "step": 1,
            },
            {
                "name": "freq",
                "label": "Frequency",
                "type": "number",
                "input_type": "number",
                "required": True,
                "placeholder": "86.3",
                "help": "Observing frequency. Example: 86.3.",
                "step": "any",
            },
        ],
    },
    "meteo": {
        "name": "meteo",
        "label": "Meteo",
        "description": "Retrieve meteorological values for the selected date and hour.",
        "example": "meteo,20260116,1",
        "parameters": [
            {
                "name": "date",
                "label": "Date",
                "type": "string",
                "input_type": "text",
                "required": True,
                "placeholder": "20260116",
                "help": "Date in YYYYMMDD format. Do not prefix it with A.",
                "pattern": "^[0-9]{8}$",
            },
            {
                "name": "hour",
                "label": "Hour",
                "type": "integer",
                "input_type": "number",
                "required": True,
                "placeholder": "1",
                "help": "Hour as an integer from 0 to 23. Use 0 for the daily series when supported by the legacy backend.",
                "min": 0,
                "max": 23,
                "step": 1,
            },
        ],
    },
    "rain": {
        "name": "rain",
        "label": "Rain",
        "description": "Retrieve rain-related values for the selected date and hour.",
        "example": "rain,20260116,1",
        "parameters": [
            {
                "name": "date",
                "label": "Date",
                "type": "string",
                "input_type": "text",
                "required": True,
                "placeholder": "20260116",
                "help": "Date in YYYYMMDD format. Do not prefix it with A.",
                "pattern": "^[0-9]{8}$",
            },
            {
                "name": "hour",
                "label": "Hour",
                "type": "integer",
                "input_type": "number",
                "required": True,
                "placeholder": "1",
                "help": "Hour as an integer from 0 to 23. Use 0 for the daily series when supported by the legacy backend.",
                "min": 0,
                "max": 23,
                "step": 1,
            },
        ],
    },
    "tsys": {
        "name": "tsys",
        "label": "Tsys",
        "description": "Estimate system temperature from date, hour, frequency, elevation angle, efficiency, and receiver temperature.",
        "example": "tsys,20260116,1,86.3,45.0,0.95,50.0",
        "parameters": [
            {
                "name": "date",
                "label": "Date",
                "type": "string",
                "input_type": "text",
                "required": True,
                "placeholder": "20260116",
                "help": "Date in YYYYMMDD format. Do not prefix it with A.",
                "pattern": "^[0-9]{8}$",
            },
            {
                "name": "hour",
                "label": "Hour",
                "type": "integer",
                "input_type": "number",
                "required": True,
                "placeholder": "1",
                "help": "Hour as an integer from 0 to 23. Use 0 for the daily series when supported by the legacy backend.",
                "min": 0,
                "max": 23,
                "step": 1,
            },
            {
                "name": "freq",
                "label": "Frequency",
                "type": "number",
                "input_type": "number",
                "required": True,
                "placeholder": "86.3",
                "help": "Observing frequency. Example: 86.3.",
                "step": "any",
            },
            {
                "name": "theta",
                "label": "Elevation angle",
                "type": "number",
                "input_type": "number",
                "required": True,
                "placeholder": "45.0",
                "help": "Elevation angle in degrees. Example: 45.0.",
                "step": "any",
            },
            {
                "name": "eta",
                "label": "Efficiency",
                "type": "number",
                "input_type": "number",
                "required": True,
                "placeholder": "0.95",
                "help": "Efficiency value. Example: 0.95.",
                "step": "any",
            },
            {
                "name": "trec",
                "label": "Receiver temperature",
                "type": "number",
                "input_type": "number",
                "required": True,
                "placeholder": "50.0",
                "help": "Receiver temperature. Example: 50.0.",
                "step": "any",
            },
        ],
    },
}


def get_legacy_command_catalog() -> List[Dict[str, Any]]:
    return [deepcopy(LEGACY_COMMANDS[name]) for name in LEGACY_COMMANDS]
