from __future__ import annotations

from typing import Any, Dict, List


COMMAND_CATALOG: List[Dict[str, Any]] = [
    {
        "name": "iwv",
        "label": "IWV",
        "description": "Compute integrated water vapor products from a legacy data file.",
        "example": "iwv,2026011600,1",
        "parameters": [
            {
                "name": "data_timestamp",
                "label": "Data file timestamp",
                "type": "text",
                "required": True,
                "pattern": "^[0-9]{10}$",
                "placeholder": "2026011600",
                "example": "2026011600",
                "help": "Use the data filename without the .dat extension. Format: YYYYMMDDHH. Example: 2026011600 for 2026011600.dat.",
            },
            {
                "name": "hour",
                "label": "Hour / epoch selector",
                "type": "integer",
                "required": True,
                "min": 0,
                "placeholder": "1",
                "example": "1",
                "help": "Use 1-23 for a single point. Use 0 for the full time series when supported by the command.",
            },
        ],
    },
    {
        "name": "opacity",
        "label": "Opacity",
        "description": "Compute atmospheric opacity for a frequency from a legacy data file.",
        "example": "opacity,2026011600,1,86.3",
        "parameters": [
            {
                "name": "data_timestamp",
                "label": "Data file timestamp",
                "type": "text",
                "required": True,
                "pattern": "^[0-9]{10}$",
                "placeholder": "2026011600",
                "example": "2026011600",
                "help": "Use the data filename without the .dat extension. Format: YYYYMMDDHH. Example: 2026011600 for 2026011600.dat.",
            },
            {
                "name": "hour",
                "label": "Hour / epoch selector",
                "type": "integer",
                "required": True,
                "min": 0,
                "placeholder": "1",
                "example": "1",
                "help": "Use 1-23 for a single point. Use 0 for the full time series when supported by the command.",
            },
            {
                "name": "freq",
                "label": "Frequency",
                "type": "number",
                "required": True,
                "step": "any",
                "placeholder": "86.3",
                "example": "86.3",
                "help": "Observing frequency used by the legacy opacity calculation.",
            },
        ],
    },
    {
        "name": "meteo",
        "label": "Meteo",
        "description": "Extract meteorological values from a legacy data file.",
        "example": "meteo,2026011600,1",
        "parameters": [
            {
                "name": "data_timestamp",
                "label": "Data file timestamp",
                "type": "text",
                "required": True,
                "pattern": "^[0-9]{10}$",
                "placeholder": "2026011600",
                "example": "2026011600",
                "help": "Use the data filename without the .dat extension. Format: YYYYMMDDHH. Example: 2026011600 for 2026011600.dat.",
            },
            {
                "name": "hour",
                "label": "Hour / epoch selector",
                "type": "integer",
                "required": True,
                "min": 0,
                "placeholder": "1",
                "example": "1",
                "help": "Use 1-23 for a single point. Use 0 for the full time series when supported by the command.",
            },
        ],
    },
    {
        "name": "rain",
        "label": "Rain",
        "description": "Extract rain information from a legacy data file.",
        "example": "rain,2026011600,1",
        "parameters": [
            {
                "name": "data_timestamp",
                "label": "Data file timestamp",
                "type": "text",
                "required": True,
                "pattern": "^[0-9]{10}$",
                "placeholder": "2026011600",
                "example": "2026011600",
                "help": "Use the data filename without the .dat extension. Format: YYYYMMDDHH. Example: 2026011600 for 2026011600.dat.",
            },
            {
                "name": "hour",
                "label": "Hour / epoch selector",
                "type": "integer",
                "required": True,
                "min": 0,
                "placeholder": "1",
                "example": "1",
                "help": "Use 1-23 for a single point. Use 0 for the full time series when supported by the command.",
            },
        ],
    },
    {
        "name": "tsys",
        "label": "Tsys",
        "description": "Estimate system temperature from legacy atmospheric data and receiver parameters.",
        "example": "tsys,2026011600,1,86.3,45.0,0.95,50.0",
        "parameters": [
            {
                "name": "data_timestamp",
                "label": "Data file timestamp",
                "type": "text",
                "required": True,
                "pattern": "^[0-9]{10}$",
                "placeholder": "2026011600",
                "example": "2026011600",
                "help": "Use the data filename without the .dat extension. Format: YYYYMMDDHH. Example: 2026011600 for 2026011600.dat.",
            },
            {
                "name": "hour",
                "label": "Hour / epoch selector",
                "type": "integer",
                "required": True,
                "min": 0,
                "placeholder": "1",
                "example": "1",
                "help": "Use 1-23 for a single point. Use 0 for the full time series when supported by the command.",
            },
            {
                "name": "freq",
                "label": "Frequency",
                "type": "number",
                "required": True,
                "step": "any",
                "placeholder": "86.3",
                "example": "86.3",
                "help": "Observing frequency used by the legacy calculation.",
            },
            {
                "name": "theta",
                "label": "Theta",
                "type": "number",
                "required": True,
                "step": "any",
                "placeholder": "45.0",
                "example": "45.0",
                "help": "Elevation angle in degrees.",
            },
            {
                "name": "eta",
                "label": "Eta",
                "type": "number",
                "required": True,
                "step": "any",
                "placeholder": "0.95",
                "example": "0.95",
                "help": "Efficiency parameter used by the legacy calculation.",
            },
            {
                "name": "trec",
                "label": "Trec",
                "type": "number",
                "required": True,
                "step": "any",
                "placeholder": "50.0",
                "example": "50.0",
                "help": "Receiver temperature used by the legacy calculation.",
            },
        ],
    },
]


def get_legacy_command_catalog() -> List[Dict[str, Any]]:
    return COMMAND_CATALOG
